name: BigData Ingestion Workflow

# Se ejecuta cuando haces push o pull request a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Configura el ambiente y los jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checa el código en el repositorio
    - name: Check out repository
      uses: actions/checkout@v3

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Instala las dependencias del proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Corre el script de ingestion.py
    - name: Run Ingestion script
      run: |
        python src/ingestion.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}

    # Corre el script de cleaning.py
    - name: Run Cleaning script
      run: |
        python src/cleaning.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
