name: BigData Ingestion Workflow

# Se ejecuta cuando haces push o pull request a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Añadir esta sección de permisos
permissions:
  contents: write

# Configura el ambiente y los jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checa el código en el repositorio
    - name: Check out repository
      uses: actions/checkout@v3

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Instala las dependencias del proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Corre el script de ingestion.py
    - name: Run Ingestion script
      run: |
        python src/ingestion.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

    # Corre el script de cleaning.py
    - name: Run Cleaning script
      run: |
        python src/cleaning.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

    # Corre el script de enrichment.py
    - name: Run Enrichment script
      run: |
        python src/enrichement.py
      env:
        TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

    # Commit y push de los archivos generados
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/static/auditoria/comparative_audit_report.txt
        git add src/static/auditoria/excel_audit_report.html
        git add src/static/auditoria/sqlite_audit_report.html
        git add src/static/auditoria/cleaning_report.txt
        git add src/static/auditoria/enrichment_report.txt
        git add src/static/db/ingestion.db
        git add src/static/xlsx/tmdb_movies.xlsx
        git add src/static/xlsx/cleaned_data.xlsx
        git add src/static/xlsx/enriched_data.xlsx
        git commit -m "Actualizar archivos de ingestion, limpieza y enriquecimiento, además de auditorías [skip ci]" || echo "No changes to commit"
        git push

    # Genera la documentación
    - name: Copy audit files to docs
      run: |
        mkdir -p docs/auditoria/archivos
        cp src/static/auditoria/*.html docs/auditoria/archivos/
        cp src/static/auditoria/*.txt docs/auditoria/archivos/
        
    # Build mkdocs
    - name: Build MkDocs
      run: |
        mkdocs build
    # Instala MkDocs y el plugin de Material
    - name: Deploy MkDocs
      run: |
        mkdocs gh-deploy --force

